name: Publish to Confluence
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Publish Markdown to Confluence
        uses: markdown-confluence/publish-action@v5
        with:
          configFile: .markdown-confluence.json
          confluenceBaseUrl: https://your-confluence-instance-url
          confluenceParentId: 123456
          atlassianUserName: harry@askporter.com
          atlassianApiToken: ${{ secrets.CONFLUENCE_PASSWORD }}
